using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TrueMoon.Cobalt.Generator;

[Generator(LanguageNames.CSharp)]
public class CobaltGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var calls = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is InvocationExpressionSyntax { Expression: MemberAccessExpressionSyntax member } &&
                member.Name.Identifier.Text is "Singleton" or "Transient" or "Composite",
            static (ctx, _) => (InvocationExpressionSyntax)ctx.Node).Collect();
        context.RegisterSourceOutput(context.CompilationProvider.Combine(calls),
            static (ctx, input) => Generate(input.Left, input.Right, ctx));
    }

    private static void Generate(Compilation compilation, ImmutableArray<InvocationExpressionSyntax> calls, SourceProductionContext context)
    {
        var generated = new HashSet<string>();
        var registrations = new StringBuilder();
        foreach (var call in calls)
        {
            var model = compilation.GetSemanticModel(call.SyntaxTree);
            if (model.GetSymbolInfo(call).Symbol is not IMethodSymbol method ||
                method.ReturnType.ToDisplayString() != "TrueMoon.Services.IServicesRegistrationContext") continue;
            var lifetime = method.Name == "Transient" ? "Transient" : "Singleton";
            if (method.Name == "Composite")
            {
                if (method.TypeArguments[0] is not INamedTypeSymbol implementation) continue;
                Add(implementation, implementation, "Singleton", null);
                foreach (var alias in method.TypeArguments.Skip(1).OfType<INamedTypeSymbol>())
                    Add(alias, implementation, "Singleton", $"context.Resolve<{TypeName(implementation)}>()");
                continue;
            }
            INamedTypeSymbol? service = null;
            INamedTypeSymbol? concrete = null;
            if (method.TypeArguments.Length > 0)
            {
                // Runtime factories already have their own resolver and must not publish global construction code.
                if (method.Parameters.Length != 0) continue;
                service = method.TypeArguments[0] as INamedTypeSymbol;
                concrete = method.TypeArguments.Length == 2 ? method.TypeArguments[1] as INamedTypeSymbol : service;
            }
            else
            {
                var args = call.ArgumentList.Arguments;
                if (args.Count > 0 && args[0].Expression is TypeOfExpressionSyntax first)
                    service = model.GetTypeInfo(first.Type).Type as INamedTypeSymbol;
                if (args.Count > 1 && args[1].Expression is TypeOfExpressionSyntax second)
                    concrete = model.GetTypeInfo(second.Type).Type as INamedTypeSymbol;
                else concrete = service;
            }
            if (service != null && concrete != null) Add(service, concrete, lifetime, null);
        }
        if (generated.Count == 0) return;
        context.AddSource("CobaltResolversRegistration.g.cs", $@"
// auto-generated by TrueMoon.Cobalt.Generator
namespace {Namespace(compilation)};
public static class CobaltResolversRegistration
{{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    public static void Init()
    {{
{registrations}    }}
}}");

        void Add(INamedTypeSymbol service, INamedTypeSymbol implementation, string lifetime, string? alias)
        {
            var name = Identifier(TypeName(service)) + "_" + Identifier(TypeName(implementation)) + "_" + lifetime + (alias == null ? "Resolver" : "AliasResolver");
            if (!generated.Add(name)) return;
            var open = service.IsUnboundGenericType;
            var source = open ? GenericSource(compilation, name, implementation, lifetime) : Source(compilation, name, service, implementation, lifetime, alias);
            context.AddSource(name + ".g.cs", source);
            registrations.AppendLine($"        global::TrueMoon.Cobalt.ServiceResolvers.Shared.Add(typeof({TypeName(service)}), typeof({TypeName(implementation)}), global::TrueMoon.Cobalt.ServiceLifetime.{lifetime}, () => new {name}());");
        }
    }

    private static string Source(Compilation compilation, string name, INamedTypeSymbol service, INamedTypeSymbol implementation, string lifetime, string? alias)
    {
        var constructor = implementation.InstanceConstructors.Where(c => c.DeclaredAccessibility == Accessibility.Public)
            .OrderByDescending(c => c.Parameters.Length).FirstOrDefault();
        var arguments = constructor == null ? "" : string.Join(", ", constructor.Parameters.Select(p =>
            $"context.{(p.NullableAnnotation == NullableAnnotation.Annotated ? "TryResolve" : "Resolve")}<{TypeName(p.Type)}>()"));
        var create = alias ?? $"new {TypeName(implementation)}({arguments})";
        var singleton = lifetime == "Singleton";
        return $@"
// auto-generated by TrueMoon.Cobalt.Generator
#nullable enable
namespace {Namespace(compilation)};
public class {name} : global::TrueMoon.Cobalt.IResolver<{TypeName(service)}, {TypeName(implementation)}>, global::TrueMoon.Cobalt.IObjectResolver
{{
    {(singleton ? $"private readonly object _lock = new();\n    private {TypeName(service)}? _instance;" : "")}
    public global::TrueMoon.Cobalt.ServiceLifetime ServiceLifetime => global::TrueMoon.Cobalt.ServiceLifetime.{lifetime};
    public bool IsServiceDisposable => true;
    public {TypeName(service)} Resolve(global::TrueMoon.Services.IServiceResolver context)
    {{
        {(singleton ? $"lock (_lock) return _instance ??= {create};" : $"return {create};")}
    }}
    object? global::TrueMoon.Cobalt.IObjectResolver.Resolve(global::TrueMoon.Services.IServiceResolver context) => Resolve(context);
}}
";
    }

    private static string GenericSource(Compilation compilation, string name, INamedTypeSymbol implementation, string lifetime)
    {
        var singleton = lifetime == "Singleton";
        return $@"
// auto-generated by TrueMoon.Cobalt.Generator
#nullable enable
namespace {Namespace(compilation)};
public class {name} : global::TrueMoon.Cobalt.IGenericResolver
{{
    private readonly object _lock = new();
    {(singleton ? "private readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> _instances = new();" : "")}
    public global::TrueMoon.Cobalt.ServiceLifetime ServiceLifetime => global::TrueMoon.Cobalt.ServiceLifetime.{lifetime};
    public bool IsServiceDisposable => true;
    public object? Resolve(global::System.Type[] arguments, global::TrueMoon.Services.IServiceResolver context)
    {{
        lock (_lock)
        {{
            var type = typeof({TypeName(implementation)}).MakeGenericType(arguments);
            {(singleton ? "if (_instances.TryGetValue(type, out var existing)) return existing;" : "")}
            var constructors = type.GetConstructors();
            global::System.Array.Sort(constructors, (a, b) => b.GetParameters().Length.CompareTo(a.GetParameters().Length));
            var constructor = constructors[0];
            var parameters = constructor.GetParameters();
            var values = new object?[parameters.Length];
            for (var index = 0; index < parameters.Length; index++)
            {{
                var parameter = parameters[index];
                values[index] = context.GetService(parameter.ParameterType);
                if (values[index] == null)
                {{
                    if (parameter.HasDefaultValue) values[index] = parameter.DefaultValue;
                    else if (new global::System.Reflection.NullabilityInfoContext().Create(parameter).ReadState != global::System.Reflection.NullabilityState.Nullable)
                        throw new global::TrueMoon.Cobalt.ServiceResolvingException(parameter.ParameterType);
                }}
            }}
            var item = constructor.Invoke(values);
            {(singleton ? "_instances.Add(type, item);" : "")}
            return item;
        }}
    }}
}}
";
    }

    private static string Namespace(Compilation compilation) => Identifier(compilation.AssemblyName ?? "Assembly") + ".Cobalt.Generated";
    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    private static string Identifier(string value)
    {
        // Encode punctuation as well as underscores, so namespace/type/lifetime combinations never collide.
        var result = new StringBuilder("R");
        foreach (var character in value)
            if (char.IsLetterOrDigit(character)) result.Append(character);
            else result.Append('_').Append(((int)character).ToString("X4"));
        return result.ToString();
    }
}
