<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TF)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TrueMoon.Alloy/TrueMoon.Alloy.csproj" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
</Project>
