<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TF)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TrueMoon.Alloy/TrueMoon.Alloy.csproj" />
    <PackageReference Include="Silk.NET" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" />
  </ItemGroup>
</Project>
